### ISSUE TITLE
Sample app does not build for iOS Swift.

### ISSUE THREAD

**Issue by stewartschillingsdi** [adobe/aepsdk-sample-app-ios#23]
### Expected Behaviour
Sample app should build for iOS Swift.

### Actual Behaviour
Sample app does not build for iOS Swift.

### Reproduce Scenario (including but not limited to)
> git clone https://github.com/adobe/aepsdk-sample-app-ios.git
> cd aepsdk-sample-app-ios/Swift
> pod install
> open AEPSampleApp.xcworkspace
(in xCode) : Select iPhone 11 simulator
(in xCode) : Click the "Play" Icon to build and run for the selected simulator.
=========
Build Fails: 
Analytics.swift (line 160)
Edge.sendEvent(experienceEvent: experienceEvent, responseHandler: nil)
 **Extraneous argument label 'responseHandler:' in call**
=========

After a manual fix to this line, the build then succeeds. 

#### Steps to Reproduce
See above.
#### Platform and Version
Mac OS Big Sur 11.1 (20C69)
xCode Version 12.3 (12C33)

**Comment by praveek** [comment]
@stewartschillingsdi This has been fixed.
