### ISSUE TITLE
Update with ACP example for Adobe Experience Platform Assurance

### ISSUE THREAD

**Issue by Brontojoris** [adobe/aepsdk-sample-app-ios#50]
Please update the documentation that describes how to implement AEP Assurance when using ACP v2.x SDKs

https://aep-sdks.gitbook.io/docs/foundation-extensions/adobe-experience-platform-assurance

**Comment by spoorthipujariadobe** [comment]
@Brontojoris you can find the instructions on how to implement AEP Assurance using ACP SDKs under `iOS (AEP 1.x)` tab in the documentation link you shared
