### ISSUE TITLE
Swift build failed with "Type 'Identity' has no member 'getUrlVariables'"

### ISSUE THREAD

**Issue by hokugawa** [adobe/aepsdk-sample-app-ios#54]
### Expected Behaviour
Build without an error

### Actual Behaviour
Build failed with the following error.
`.../aepsdk-sample-app-ios/Swift/AEPSampleApp/EdgeIdentityView.swift:138:50: Type 'Identity' has no member 'getUrlVariables'`

To fix the problem, need to use the newer `AEPEdgeIdentity` pod.
e.g.
In Podfile.lock

change from
`  - AEPEdgeIdentity (1.0.1):`
to
`  - AEPEdgeIdentity (1.1.0):`

#### Steps to Reproduce
Follow https://github.com/adobe/aepsdk-sample-app-ios#swift

<img width="1512" alt="Screen Shot 2022-07-29 at 10 20 49 AM" src="https://user-images.githubusercontent.com/9561388/181781449-0005120d-c4ce-4a73-aca7-65ef1ecb7532.png">

**Comment by addb** [comment]
Hi @hokugawa 

The getUrlVariables API was added in 1.1.0. In order to use that API you need to update to 1.1.0.
Release notes: https://github.com/adobe/aepsdk-edgeidentity-ios/releases/tag/1.1.0

To update pods:
```
pod repo update
pod update
```

Please let us know if you have any additional questions.

Thanks,
Arjun

**Comment by addb** [comment]
Hi @hokugawa, 

Thanks for bringing it to our notice. We will update our pods. On the other hand if you wish to open the PR for the change, you are more than welcome to do so. We accept external contributions as well.

Thanks,
Arjun

**Comment by addb** [comment]
Fixed in https://github.com/adobe/aepsdk-sample-app-ios/pull/55
