### ISSUE TITLE
AEPMobileTarget getThirdPartyId getting always "nil" value

### ISSUE THREAD

**Issue by shravanteegala** [adobe/aepsdk-sample-app-ios#59]
AEPMobileTarget getThirdPartyId:^(NSString * _Nullable getThirdPartyId, NSError *error) {
        if (error != nil) {
            // Handle error
            return;
        }
        
        NSLog(@"%@", getThirdPartyId);
    }];

team, AEPMobileTarget getThirdPartyId getting always "nil" value.
how i can get value insteadOf nil.

**Comment by cacheung** [comment]
@shravanteegala please check if you have the initial setup and Environment File ID setup properly by following the [documentation](https://github.com/adobe/aepsdk-analytics-android/pull/59).

**Comment by shravanteegala** [comment]
[AEPMobileTarget getThirdPartyId:^(NSString *thirdPartyID, NSError *error)] {

   NSLog(@"thirdPartyId  is : @", thirdPartyID)
}];

// ouput: null

getting below Log console .
[AEP SDK WARNING - Unable to handle response, No third party id available.]

[AEPMobileTarget getTntId:^(NSString *tntID, NSError *error)] {

   NSLog(@"tntID  is : @", tntID)
}];

// output : null
getting below Log console .
[AEP SDK WARNING - Unable to handle response, No tntID available.]

[AEPAnylatics getVisitorIdentifier:^(NSString *visitorID, NSError *error)] {

   NSLog(@"visitorID  is : @",visitorID)
}];

// ouput: (null)
getting below Log console .
[AEP SDK WARNING - Unable to handle response, No getVisitorIdentifier available.]

**Comment by cacheung** [comment]
@shravanteegala 
AEPMobileTarget getThirdPartyId - if there is no custom third party ID was previously set, it will show nil.  Have you set it?
https://developer.adobe.com/client-sdks/documentation/adobe-target/api-reference/#getthirdpartyid

AEPMobileTarget getTntId - The tntId is returned in the network response after a successful call to prefetchContent or retrieveLocationContent, have you call them?
https://developer.adobe.com/client-sdks/documentation/adobe-target/api-reference/#gettntid

AEPAnylatics getVisitorIdentifier - it gets the custom visitor identifier which previously set in setVisitorIdentifier.  Have you set it?
https://developer.adobe.com/client-sdks/documentation/adobe-analytics/api-reference/#getvisitoridentifier

If you did set them already,  we might need to take a look of your Environment File ID.

**Comment by shravanteegala** [comment]
thank you @cacheung .
